### ISSUE TITLE
gqt integration?

### ISSUE THREAD

**Issue by staalmannen** [e8johan/gtk-made-qt#1]
Are all features of gqt integrated? I mirrored the old one here on github before finding this.

In principle I think having shim headers might be a good idea so that source does not have to be modified before the first compile attempt.

for example if headers are found in /usr/include/qt5/gqt/{gtk,gdk}

then gtk.h and other headers expected by GTK applications could point to gtk-made-qt.h by 
"#include "../gtk-made-qt.h"
Perhaps hybrid approach where some things are in the shim GTK headers and other things in the special gtk-made-qt header.

For example: Stuff that easily can be handled by the preprocessor could be in the shim headers,
(stuff of type "#define FOO BAR" )
while stuff better handled by the linker, for example stuff that requires a small function to be written to emulate GTK behavior is kept in the gtk-made-qt header (and associate library)

Sorry if I am out of line... just brainstorming :)

**Comment by staalmannen** [comment]
Apparently there is a 3rd implementation of GTK-to-Qt conversion
https://madebyryan.blogspot.be/2011/07/convert-gtk-application-into-qt.html

https://madebyryan.blogspot.be/2011/12/qt-wrapper-for-gtk-nearly-done.html

but no source is shared :(

I think it in general would be cool to build code from different widget toolkits directly on Qt without source changes. Back in Qt3 there was a Motif compatibility module but it did not implement Xt.

If you are aware of any other projects that have taken this further, I am curious to know about them :)

**Comment by e8johan** [comment]
This is basically an experiment to map the "difficult" parts of GTK+ to Qt, e.g. menus (actions) and the QGtkCallBridge, for propagating events from Qt to GTK+.

Here are some of my original blogs:

http://www.thelins.se/johan/blog/2010/01/gtk-made-qt/
http://www.thelins.se/johan/blog/2010/01/qt-as-gtk-again/

Also, I looked for Robin Burchell's code, but the repository is a 404 now...

If you want to work in this and improve it, feel free to do so. I happily accept merge requests!

**Comment by staalmannen** [comment]
I have a mirror of gqt on github

https://github.com/staalmannen/gqt

I will see if I can merge this and gtk-made-qt in some sensible way.

**Comment by e8johan** [comment]
Cool! I'm looking forward to see what you come up with!

On Tue, Jun 28, 2016, 14:52 Jens Staal notifications@github.com wrote:

> I have a mirror of gqt on github
> 
> https://github.com/staalmannen/gqt
> 
> I will see if I can merge this and gtk-made-qt in some sensible way.
> 
> On tisdag 28 juni 2016 kl. 04:49:46 CEST Johan Thelin wrote:
> 
> > This is basically an experiment to map the "difficult" parts of GTK+ to
> > Qt,
> > e.g. menus (actions) and the QGtkCallBridge, for propagating events from
> > Qt
> > to GTK+.
> > 
> > Here are some of my original blogs:
> > 
> > http://www.thelins.se/johan/blog/2010/01/gtk-made-qt/
> > http://www.thelins.se/johan/blog/2010/01/qt-as-gtk-again/
> > 
> > Also, I looked for Robin Burchell's code, but the repository is a 404
> > now...
> > 
> > If you want to work in this and improve it, feel free to do so. I happily
> > accept merge requests!
> > 
> > ---
> > 
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/e8johan/gtk-made-qt/issues/1#issuecomment-229026688
> 
> —
> You are receiving this because you modified the open/close state.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/e8johan/gtk-made-qt/issues/1#issuecomment-229039614,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABpw8_QY6zxRD3QUOUx87yjtSwCASPypks5qQRj5gaJpZM4CZcHO
> .
> 
> ## 

---

Johan Thelin

Recommended on-line reading:
http://www.thelins.se | http://www.foss-gbg.se
Recommended off-line reading:
The Foundations of Qt Development (ISBN: 1-59059-831-8)
